# Added by Toolbox App
export PATH="$PATH:/Users/marijn/Library/Application Support/JetBrains/Toolbox/scripts"

export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

eval "$(/opt/homebrew/bin/brew shellenv)"

export KUBE_EDITOR='open -a "Sublime Text" --wait'export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"
